// Copyright (c) 2014 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
  Constructor(DOMString typeArg, optional CompositionEventInit eventInitDict),
]
interface CompositionEvent : UiEvent {
  readonly attribute long caret;
  readonly attribute DOMString data;
  readonly attribute CompositionSpan[] spans;
};
