dictionary EventInit : Foo {
  int bubbles = 123;
  boolean cancelable = false;
  short foo;
};

[Constructor(DOMString typeArg, optional EventInit eventInitDict)]
interface Event {
  // DOM PhaseType
  const unsigned short NONE = 0;
  const unsigned short CAPTURING_PHASE = 1;
  const unsigned short AT_TARGET = 2;
  const unsigned short BUBBLING_PHASE = 3;

  readonly attribute DOMString type;
  readonly attribute EventTarget target;
  readonly attribute EventTarget currentTarget;
  readonly attribute unsigned short eventPhase;
  readonly attribute boolean bubbles;
  readonly attribute boolean cancelable;
  readonly attribute DOMTimeStamp timeStamp;
};
