// Copyright (c) 2014 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
  Constructor(DOMString typeArg, optional EventInit eventInitDict),
]
interface Event {
  // DOM PhaseType
  const unsigned short NONE = 0;
  const unsigned short CAPTURING_PHASE = 1;
  const unsigned short AT_TARGET = 2;
  const unsigned short BUBBLING_PHASE = 3;

  readonly attribute boolean bubbles;
  readonly attribute boolean cancelable;
  readonly attribute boolean defaultPrevented;
  readonly attribute EventTarget? currentTarget;
  readonly attribute unsigned short eventPhase;
  readonly attribute EventTarget? target;
  readonly attribute DOMTimeStamp timeStamp;
  readonly attribute DOMString type;

  void preventDefault();
  void stopImmediatePropagation();
  void stopPropagation();
};
