// Copyright (c) 2014 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

dictionary KeyboardEventInit : UiEventInit {
  boolean altKey = false;
  //unsigned long charCode = 0;
  boolean ctrlKey = false;
  unsigned long keyCode = 0;
  unsigned long location = 0;
  boolean metaKey = false;
  boolean repeat = false;
  boolean shiftKey = false;
  //unsigned long which = 0;
};
