// Copyright (c) 2014 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
  Constructor(DOMString typeArg, WheelEventInit eventInitDict),
  Constructor(DOMString typeArg)
]
interface WheelEvent : MouseEvent {
  readonly attribute double deltaX;
  readonly attribute double deltaY;
  readonly attribute double deltaZ;
  readonly attribute unsigned long deltaMode;
};
