// Copyright (c) 2014 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
  CustomConstructor(),
  CustomConstructor(DOMString label),
  CustomConstructor(DOMString label, TextDecoderOptions options)
]
interface TextDecoder {
  readonly attribute DOMString encoding;

  DOMString decode();
  DOMString decode(ArrayBufferView input);
  DOMString decode(ArrayBufferView input, TextDecodeOptions options);
};
