// Copyright (c) 2014 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
  CustomConstructor(optional DOMString label,
                    optional TextDecoderOptions options)
]
interface TextDecoder {
  readonly attribute DOMString encoding;

  DOMString decode(optional ArrayBufferView input,
                   optional TextDecodeOptions options);
};
