// Copyright (c) 2013-2014 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

interface DataTransferItemList {
  readonly attribute unsigned long length;

  //getter DataTransferItem (unsigned long index);

  [RaisesException]
  DataTransferItem get(unsigned long index);

  //DataTransferItem? add(DataTransferData data, DOMString type);
  void add(DataTransferData data, DOMString type);

  void clear();

  [RaisesException]
  void remove(unsigned long index);
};
