// Copyright (c) 1996-2014 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[ImplementedAs=JavaScript, Constructor(TextDocument document, object options)]
interface Lexer {
  attribute long changedOffset;
  attribute long debug;
  attribute TextMutationObserver mutationObserver_;
  attribute TextRange? range;
  attribute long scanOffset;
  attribute long state;
  attribute DOMString syntax;

  long adjustScanOffset(long hint);
  void detach();
  void didChangeScanOffset();
  DOMString extractWord(TextRange range, object token);
  void doColor(long hint);
  DOMString finishState();
  void setSyntax(/* lexers.Token */ object token);
  void startToken(long state, DOMString syntax);
};
