// Copyright (c) 2013-2014 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[Constructor(Range range)]
interface TextWindow : DocumentWindow {
  attribute float zoom;

  [ImplementedAs=ComputeMotion]
  long compute_(long method, optional long offset, optional long count,
                optional Point point);

  [ImplementedAs=HitTestTextPosition]
  Rect hitTestTextPosition_(long offset);

  void makeSelectionVisible();

  [ImplementedAs=MapPointToPosition]
  Promise<long> mapPointToPosition_(float x, float y);

  [ImplementedAs=Reconvert]
  void reconvert_(DOMString text);

  void scroll(long direction);
};
