// Copyright (c) 2016 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

interface VisualWindow : Window {
  [ImplementedAs=JavaScript]
  static void handleEvent(Event event);

  // Returns node sequence id under specified point.
  [ImplementedAs=HitTest]
  long hitTest_(long point_x, long point_y);

  // Construct new |VisualWindow| and returns it.
  static VisualWindow newWindow(NodeHandle documentHandle);
};
