// Copyright (c) 2016 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

interface WinResource {
  [CallWith=ScriptHost]
  Promise close();

  [CallWith=ScriptHost]
  Promise getResourceNames(DOMString type);

  [CallWith=ScriptHost]
  Promise load(DOMString type, DOMString name, Uint8Array buffer);

  static long lookupIcon(Uint8Array iconSpec, long iconSize);

  [CallWith=ScriptHost]
  static Promise open(DOMString commandLine);
};
