// Copyright (c) 2014 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
  CallWith=ScriptHost,
  Constructor(Form form, optional FormWindowInit init)
]
interface FormWindow : Window {
  readonly attribute Form form;
};
