// Copyright (c) 1996-2014 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

interface FormControl : ViewEventTarget {
  [ImplementedAs=JavaScript] static void handleEvent(Event event);

  [ImplementedAs=JavaScript] attribute DOMString accessKey;
  attribute float clientHeight;
  attribute float clientLeft;
  attribute float clientTop;
  attribute float clientWidth;
  attribute boolean disabled;
  readonly attribute Form? form;
  readonly attribute DOMString name;

  [ImplementedAs=JavaScript] boolean canFocus();
  [ImplementedAs=JavaScript] void focus();
};
