// Copyright (c) 1996-2014 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

interface FormControl : ViewEventTarget {
  [ImplementedAs=JavaScript] static void handleEvent(Event event);

  [ImplementedAs=JavaScript] attribute DOMString accessKey;
  attribute long clientHeight;
  attribute long clientLeft;
  attribute long clientTop;
  attribute long clientWidth;
  attribute bool disabled;
  readonly attribute Form? form;
  readonly attribute DOMString name;

  [ImplementedAs=JavaScript] bool canFocus();
  [ImplementedAs=JavaScript] void focus();
};
