// Copyright (c) 2014 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[Constructor()]
interface TextFieldControl : FormControl {
  [ImplementedAs=JavaScript]
  attribute string lastChangeEventValue_;

  readonly attribute TextFieldSelection selection;

  attribute float scroll_left;

  [ImplementedAs=JavaScript]
  attribute DOMString value;

  [ImplementedAs=value]
  attribute DOMString value_;

  long mapPointToOffset(float x, float y);
};
