// Copyright (c) 2014 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
  ImplementedAs=JavaScript,
  Constructor(TextFieldControl control)
]
interface TextFieldRange {
  readonly attribute boolean collapsed;
  readonly attribute TextFieldControl control;
  attribute long end;
  attribute long start;
  attribute DOMString text;

  void collapseTo(long offset);
};
