// Copyright (c) 2015 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[JsNamespace=Os]
interface Directory {
  Promise<FileInfo[]> read(long numRead);
  void close();

  // |dirName| is the starting directory to enumerate for. It may or may not
  // end in a directory separator.
  static Promise<Directory> open(DOMString dirName);
};
