// Copyright (c) 1996-2014 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
  ImplementedAs=JavaScript,
  Constructor(DOMString name, Function lexerConstructor),
]
interface Mode {
  static readonly attribute Mode defaultMode;
  static readonly attribute ExtensionToModeMap extensionMap;
  static readonly attribute NameToModeMap fileNameMap;
  static readonly attribute NameToModeMap nameMap;
  static Mode chooseMode(Document document);
  static Mode chooseModeByFileName(DOMString name);

  readonly attribute Document document;
  readonly attribute DOMString name;
  readonly attribute Keymap keymap;

  void attach(Document document);
  void detach();
  void doColor(Document document, long hint);
};
