// Copyright (c) 1996-2014 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

callback MutationCallback = void (MutationRecord[] records,
                                  MutationObserver observer);

[Constructor(MutationCallback callback)]
interface MutationObserver {
  void disconnect();
  void observe(TextDocument document, MutationObserverInit options);
  MutationRecord[] takeRecords();
};
