// Copyright (c) 2014 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    RaisesException=Constructor,
    CustomConstructor(DOMString source),
    CustomConstructor(DOMString source, RegExpInit options),
]
interface RegularExpression {
  readonly attribute boolean backward;
  readonly attribute boolean global;
  readonly attribute boolean ignoreCase;
  readonly attribute boolean matchExact;
  readonly attribute boolean matchWord;
  readonly attribute boolean multiline;
  readonly attribute DOMString source;
  readonly attribute boolean sticky;
};
