// Copyright (c) 2016 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
  JsNamespace = css, ImplementedAs = JavaScript, Constructor()
] interface CSSStyleSheet {
  readonly attribute FrozenArray<CSSRule> cssRules;
  readonly attribute DOMString type;

  void appendRule(CSSStyleRule rule);
  void deleteRule(unsigned long index);
  void insertRule(CSSStyleRule rule, unsigned long index);
};
