// Copyright (c) 1996-2014 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[Constructor(optional TextStyleSheet parentStyleSheet)]
interface TextStyleSheet {
  readonly TextStyleSheet? parentStyleSheet;
  void AddRule(DOMString selector, TextStyle style);
  TextStyle? QueryRule(DOMString selector);
  void RemoveRule(DOMString selector);
};
