// Copyright (c) 2016 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
  JsNamespace=visuals,
  ImplementedAs=JavaScript,
  Constructor(DOMString selectorText),
]
interface CSSRuleBuilder {
  CSSRuleBuilder backgroundColor(DOMString color);
  CSSRuleBuilder border(DOMString color,
                        long width1,
                        optional long widht2,
                        optional long widht3,
                        optional long widht4);
  CSSStyleRule build();
  CSSRuleBuilder display(DOMString display);
  CSSRuleBuilder fontSize(long fontSize);
  CSSRuleBuilder height(long fontSize);
  CSSRuleBuilder padding(long width1,
                         optional long widht2,
                         optional long widht3,
                         optional long widht4);
  CSSRuleBuilder margin(long width1,
                        optional long widht2,
                        optional long widht3,
                        optional long widht4);
  CSSRuleBuilder width(long fontSize);
  static CSSRuleBuilder selector(DOMString selectorText);
};
