// Copyright (c) 2016 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[Constructor()]
interface CSSStyleSheetHandle {
  long countRules();
  void deleteRule(long index);
  Map ruleAt(long index)
  void insertRule(DOMString selectorText, Map rawStyle, long index);
};
