// Copyright (c) 2016 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
  JsNamespace = visuals, ImplementedAs = JavaScript, Constructor()
] interface Document : Node {
  Element createElement(DOMString tagName, optional DOMString id);
  Image createImage(ImageData data);
  Text createText(DOMString data);
};
