// Copyright (c) 2016 Project Vogue. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

interface NodeHandle {
  static void addClass(NodeHandle parent, DOMString className);
  static void appendChild(NodeHandle parent, NodeHandle node);
  static NodeHandle createDocument();
  static NodeHandle createElement(NodeHandle document, DOMString tagName,
                                  DOMString id);
  static NodeHandle createText(NodeHandle document, DOMString data);
  static Map getInlineStyle(NodeHandle handle);
  static void insertBefore(NodeHandle parent, NodeHandle node, NodeHandle child);
  static void removeChild(NodeHandle parent, NodeHandle child);
  static void removeClass(NodeHandle parent, DOMString className);
  static void  setInlineStyle(NodeHandle handle, Map rawStyle);

  readonly attribute long id;
};
